name: First-WorkFlow

on: 
  push:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Current Directory
        run: pwd

      - name: Current User
        run: whoami

      - name: Machine Name
        run: hostname

      - name: List files
        run: ls
